config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboards#index'
  get 'about' => 'dashboards#about', as: 'about'
  get 'what_to_pack' => 'dashboards#what_to_pack', as: 'what_to_pack'
  get 'parents_guide' => 'dashboards#parents_guide', as: 'parents_guide'
  get 'contact' => 'dashboards#contact', as: 'contact'
  post 'new_contact' => 'dashboards#new_contact', as: 'new_contact'
  get 'my_application' => 'dashboards#my_application', as: 'my_application'
  post 'search' => 'dashboards#search', as: 'search'
  get 'unihub_applications/universities_for_country' => 'unihub_applications#universities_for_country',
      as: 'universities_for_country'
  get 'unihub_applications/degrees_for_university' => 'unihub_applications#degrees_for_university',
      as: 'degrees_for_university'
  get 'unihub_applications/courses_for_degree' => 'unihub_applications#courses_for_degree',
      as: 'courses_for_degree'

  resources :universities, only: [:show]
  resources :unihub_applications
  resources :courses, only: [:show]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index
    @universities = University.all.order(created_at: :desc).page(params[:page]).per(9)
  end

  def my_application
    @all_applications = []
    unihub_applications = current_user.unihub_applications

    if unihub_applications.empty?
      flash[:alert] = 'You do not have any ongoing application.'
      redirect_to root_path
    else
      unihub_applications.map do |app|
        active = if app.status == 'submitted'
                   0
                 elsif app.status == 'processing'
                   1
                 elsif app.status == 'university_accepted'
                   2
                 elsif app.status == 'visa_processing'
                   3
                 elsif app.status == 'visa_approved'
                   4
                 else
                   -1
                 end
        @all_applications << [app, active]
      end
    end
  end

  def new_contact
    @contact = Contact.new(contact_params)

    if @contact.save
      UserMailer.contact_form_submitted_admin(@contact.id).deliver_now
      flash[:notice] = 'Query submitted successfully. We will be in contact with you soon.'
      redirect_to root_path
    else
      flash[:alert] = 'Could not submit your query.'
      render :contact
    end
  end

  def search
    redirect_to root_path and return if params[:search].blank? && params[:country].blank?

    @universities = if params[:search]
                      @parameter = params[:search].downcase
                      University.all.where('lower(name) LIKE :search',
                                           search: "%#{@parameter}%").order(created_at: :desc)
                    elsif params[:country] == 'All Countries'
                      University.all
                    else
                      Country.find_by(name: params[:country]).universities.order(created_at: :desc)
                    end
    @universities = @universities.page(params[:page]).per(9)
    flash[:alert] = "No Universities found with name #{params[:search]}" if @universities.nil?

    render :index
  end

  private

  def contact_params
    params.permit(:name, :email, :message)
  end
end

app/views/dashboards/about.html.erb
<div class="bg-light">
  <div class="container py-5">
    <div class="row h-100 align-items-center py-5">
      <div class="col-lg-6">
        <h1 class="display-4">A bit about UniHub</h1>
        <p class="lead text-muted mb-0">UniHub is a platform to help students make aspirational choices for their higher education. This platform 
          helps Pakistani students to get to know various universities and makes them aware of the yearly intakes 
          that are being offered by every university. Parents and students can also check the estimated course fee 
          they need to pay for the institute they wish to get admission in. UniHub is designed in such a way that it 
          can assist people in determining what the next step should be and provides guidance free of cost as they 
          pursue that step. It provides all kind of information, assistance, and guidance for enrollment procedures 
          without any consultation charges or any sort of application fee.
        </p>
      </div>
      <div class="col-lg-6 d-none d-lg-block"><img src="https://bootstrapious.com/i/snippets/sn-about/illus.png" alt="" class="img-fluid"></div>
    </div>
  </div>
</div>

<div class="bg-white py-5">
  <div class="container py-5">
    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Academic Counseling</h2>
        <p class="font-italic text-muted mb-4">Our professional team  will take into account your educational history, hobbies, and strengths, as well as 
          current  market  trend,  before  recommending  the  best  available  pathways  that  are  customized  to  meet 
          your needs.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>

    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src="https://bootstrapious.com/i/snippets/sn-about/img-2.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Securing Admission</h2>
        <p class="font-italic text-muted mb-4">UniHub personally takes care of the application procedure and help the student in putting together the 
          appropriate collection of required documentation. In addition, we follow up with the institution in a timely 
          manner to guarantee that the admissions processing is completed quickly.
        </p>
      </div>
    </div>

    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Visa Guidance</h2>
        <p class="font-italic text-muted mb-4">UniHub continue consistent communication with the embassies, consulates, and other departments that 
          are of concern. As  a consequence of this, our counsellors are up to date on  all of the  most recent rules 
          and regulations. As a direct result of this, we have a very high success record with visa applications.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>
  </div>
</div>

<div class="bg-light py-5">
  <div class="container py-5">
    <div class=" mb-4">
      <h2 class="display-4 font-weight-light">Mission & Vision</h2>
      <p class="font-italic text-muted">
        To  be  a  business  pioneer  in  Pakistan,  providing  higher  education  programs  to  students  while  assisting 
        them  in  reaching  their  goals  through professional career  counseling  without  any  additional charges.  To 
        provide experienced, thoughtful, and considerate solutions to students who are planning to study abroad, 
        and to do our best to accommodate students and their parents in achieving their goals.
      </p>
    </div>
    </div>
  </div>
</div>

app/views/dashboards/contact.html.erb
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
    </div>
    <div class="col-md-6 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="text-center">Contact Us</h4>
        </div>
        <%= form_with url: new_contact_path do |f| %>
          <div class="row mt-3">
            <div class="col-md-12">
              <%= f.label :name %>
              <%= f.text_field :name, required: true, autocomplete: "name", class: "form-control", placeholder: "Name" %>
            </div>
          </div><br />

          <div class="row mt-3">
            <div class="col-md-12">
              <%= f.label :email %>
              <%= f.text_field :email, required: true, autocomplete: "email", class: "form-control", placeholder: "Email" %>
            </div>
          </div><br />

          <div class="row mt-3">
            <div class="col-md-12">
              <%= f.label :message %>
              <%= f.text_field :message, required: true, autocomplete: "message", class: "form-control", placeholder: "Message" %>
            </div>
          </div><br />
          
          <%= f.submit "Contact", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="container">
  <section id="team" class="team team-1">
    <div class="container">
      <!--<div class="jumbotron">
        <h1 class="display-4">Welcome to UniHub!</h1>
        <p class="text-muted lead">We provide information for universities from 50+ countries. Student from all over Pakistan can count on us for their studies abroad.</p>
        <hr class="my-4">
        <p class="lead text-muted">Just fill a small application form and we will contact you right away!</p>
        <p class="lead text-muted">
          <a class="btn btn-primary btn-lg" href="<%= new_unihub_application_path %>" role="button">Apply Now</a>
        </p>
      </div>-->

      <div style="background-color: #000000; width: 100%; margin: 0 auto;" id="demo" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ul class="carousel-indicators">
          <li data-target="#demo" data-slide-to="0" class="active"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
        </ul>
        
        <!-- The slideshow -->
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="carousel-caption">
              <h1>Welcome to UniHub!</h1>
              <p class="lead">We provide information for universities from 50+ countries. Student from all over Pakistan can count on us for their studies abroad.</p>
              <hr class="my-4">
              <p class="lead">Just fill a small application form and we will contact you right away!</p>
              <p class="lead">
                <a class="btn btn-primary btn-lg" href="<%= new_unihub_application_path %>" role="button">Apply Now</a>
              </p>
            </div>
            <img style="opacity: 0.4;" src="<%= image_path('bg_1.jpg') %>" alt="Background Image" width="1100" height="500">
          </div>
          <div class="carousel-item">
            <img style="opacity: 0.4;" src="<%= image_path('bg_2.jpg') %>" alt="Background Image" width="1100" height="500">
          </div>
          <div class="carousel-item">
            <img style="opacity: 0.4;" src="<%= image_path('bg_3.jpg') %>" alt="Background Image" width="1100" height="500">
          </div>
        </div>
        
        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      </div><br />

      <h2 class="center">Universities</h2>
      <%= form_with url: search_path do |f| %>
        <div class="row">
          <div class="col-md-4 mt-3">
            <%= f.label :search_by_name %>
            <%= f.text_field :search, required: true, autocomplete: "name", class: "form-control", placeholder: "Name" %>
          </div>
          <div class="mt-5">
            <%= f.submit "Search", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>

      <%= form_with url: search_path do |f| %>
        <div class="row">
          <div class="col-md-4 mt-3">
            <%= f.label :search_by_country %>
            <%= f.select(:country, options_for_select(['All Countries'] + Country.all.map { |c| [c.name]}), {}, {class: "form-control", id: "interested_country"}) %>
          </div>
          <div class="mt-5">
            <%= f.submit "Search", class: "btn btn-primary" %>
          </div>
        </div><br />
      <% end %>

      <div class="row">

        <% @universities.each do |uni| %>
          <div class="col-xs-12 col-sm-4 col-md-4">
            <div class="card" style="width: 18rem;">
              <img width="300" height="150" class="card-img-top" src="<%= rails_blob_url(uni.images.first.image.blob) unless uni.images.first.nil? %>" alt="<%= uni.name %> Image">
              <div class="card-body">
                <h5 class="card-title"><%= uni.name %></h5>
                <p class="card-text uni-card-description lead text-muted"><%= uni.description %></p>
                <a href="<%= university_path(uni.id) %>" class="btn btn-primary">View</a>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><i class="fa fa-flag" aria-hidden="true"></i> Country <%= uni.country.name %></li>
                <li class="list-group-item"><i class="fa fa-certificate" aria-hidden="true"></i> Ranking <%= uni.world_ranking %></li>
                <li class="list-group-item"><i class="fa fa-money" aria-hidden="true"></i> Tuition Fee <%= uni.tuition_fee %></li>
                <li class="list-group-item"><i class="fa fa-graduation-cap" aria-hidden="true"></i> IELTS Score <%= uni.ielts_score == 'not_required' ? 'Not Required' : uni.ielts_score %></li>
                <li class="list-group-item"><i class="fa fa-university" aria-hidden="true"></i> Intakes <%= uni.intake %></li>
              </ul>
            </div>
            <br><br>
          </div>

          
        <% end %>

      </div>
    </div>
  </section>
  <%= paginate @universities %>
</div>

app/views/dashboards/my_application.html.erb
<% @all_applications.each_with_index do |unihub_application, i| %>
  <div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
      <div class="col-md-3 border-right">
          <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="text-black-50"><%= current_user.email %></span><span> </span></div>
      </div>
      <div class="col-md-6 border-right">
        <div class="p-3 py-5">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="text-center">Application # <%= i + 1 %></h4>
          </div>
          <% if unihub_application %>
            <div class="row mt-2">
              <div class="col-md-6">
                <label>Current Qualification</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].current_qualification %>" disabled>
              </div>

              <div class="col-md-6">
                <label>CGPA or Percentage</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].cgpa_or_percentage %>" disabled>
              </div>
            </div><br />

            <div class="row mt-3">
              <div class="col-md-12">
                <label>Current Institution</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].current_institution %>" disabled>
              </div>
            </div><br />

            <div class="row mt-3">
              <div class="col-md-12">
                <label>Interested Country</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].country.name %>" disabled>
              </div>
            </div><br />

            <div class="row mt-3">
              <div class="col-md-12">
                <label>Interested University</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].university.name %>" disabled>
              </div>
            </div><br />

            <div class="row mt-2">
              <div class="col-md-6">
                <label>Interested Qualification</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].degree.name %>" disabled>
              </div>

              <div class="col-md-6">
                <label>Interested Course</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].course.name %>" disabled>
              </div>
            </div><br />

            <div class="row mt-3">
              <div class="col-md-12">
                <label>Accomodation Required</label><br />
                <input type="text" class="form-control" value="<%= unihub_application[0].accomodation_required %>" disabled>
              </div>
            </div><br />

            <div class="row mt-3">
              <div class="col-md-12">
                <label>Application Status</label>
                <div class="progress-track">
                  <ul id="progressbar">
                    <li class="step0 <%= unihub_application[1] >= 0 ? 'active' : nil %>" id="step1">Submitted</li>
                    <li class="step0 <%= unihub_application[1] >= 1 ? 'active' : nil %> text-center" id="step2">Processing</li>
                    <li class="step0 <%= unihub_application[1] >= 2 ? 'active' : nil %> text-right" id="step3">University Accepted</li>
                    <li class="step0 <%= unihub_application[1] >= 3 ? 'active' : nil %> text-right" id="step4">Visa Processing</li>
                    <li class="step0 <%= unihub_application[1] >= 4 ? 'active' : nil %> text-right" id="step4">Visa Approved</li>
                  </ul>
                </div>
              </div>
            </div>
          <% else %>
            <div class="col-md-12">
              <h5>No Application Found</h5>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboards/parents_guide.html.erb
<br />
<div class="center container">
  <h1>Parents Guide</h1>
  <p class="lead text-muted">
    Studying in a foreign country is not only difficult for students, but also for their parents; it is far more difficult for parents to relocate their children to an altogether new location. It is certainly one of the more courageous choices that they need to make. However, this presents a wonderful opportunity for the youngsters because they will have the chance to participate in an exchange with students from other countries, which will broaden their perspectives and stimulate their thought processes. Given that this is one of the most difficult tasks that the students face, it is critical for you as a parent to provide support for them and take an active role in navigating this process.
  </p>
</div>

<div class="bg-white py-5">
  <div class="container py-5">
    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">Keep an open conversation with the child</h2>
        <p class="font-italic text-muted mb-4">It is important for parents to have honest conversations with their children about why they want to travel outside of the country. It could pertain to one's professional life or their personal life. To properly direct the youngster, it is vital to understand what it is that he is looking for.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('parent_guide/parents-role-in-the-education-of-children-with-autism.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>

    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src=<%= image_path('parent_guide/parent-doing-research.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6">
        <h2 class="font-weight-light">A thorough amount of research</h2>
        <p class="font-italic text-muted mb-4">The child is responsible for conducting some of the necessary research; however, it is the parent's duty to conduct additional investigation into the subject matter in order to guarantee that the child will be able to attend the university of his or her choice and will be successful in the chosen field of study. They are in the best position to make judgments regarding their children because they are the ones who know the most about them.
        </p>
      </div>
    </div><br /><br />

    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">Have an understanding of the Hurdles</h2>
        <p class="font-italic text-muted mb-4">It is crucial to comprehend and be aware of the difficulties faced by a parent. Therefore, you should chat to people who have sent their children to a different country. Make an effort to comprehend the things they've been through and get wisdom from the things they've overlooked while making the preparations. If the parents can be as explicit as they possibly can, it will be helpful
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('parent_guide/understanding-problem.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>

    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src=<%= image_path('parent_guide/finances.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6">
        <h2 class="font-weight-light">Information pertaining to finances</h2>
        <p class="font-italic text-muted mb-4">It is always going to be more expensive to study in one's native nation as opposed to studying in another country. Therefore, it is of the utmost importance to be aware of all of the expenditures associated with the process of studying abroad. Parents have a great deal of responsibility on their shoulders when it comes to ensuring that their children have the money to study in another country. The budget should cover not just the cost of tuition but also the cost of living, medical, and visa expenses, as well as any and all other extraneous fees. The financial requirements for studying abroad are included in the budget in the same manner as they will be necessary.
        </p>
      </div>
    </div>

    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">Concerning the Health and Safety of</h2>
        <p class="font-italic text-muted mb-4">Due to the significant disparity in the average temperatures of the two countries, they have a responsibility as parents to exercise extreme caution for the sake of their child's health. In addition, the child will not receive any assistance from the parents, which is another reason why it is crucial to take all of the appropriate safety steps to ensure that they remain healthy. Create a list of all of the prescription medications that a kid is currently taking, and consult with the child's doctor to learn about similar pharmaceutical brands that are offered at the study location.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('parent_guide/safety.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>
  </div>
</div>

app/views/dashboards/what_to_pack.html.erb
<br />
<div class="center container">
  <h1>What To Pack</h1>
</div>

<div class="bg-white py-5">
  <div class="container py-5">
    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">Passport & Requisite Visa (Plus Photocopies)</h2>
        <p class="font-italic text-muted mb-4">Be sure to keep the photocopies in a location that is separate from the original documents; doing so will make it much simpler for you to obtain a new passport and visa from the embassy in the case that the originals are misplaced or stolen.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('passport.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>

    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src=<%= image_path('medicine.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6">
        <h2 class="font-weight-light">Medications obtainable only with a doctor's prescription </h2>
        <p class="font-italic text-muted mb-4">If you take any medications that require a prescription, it is a good idea to make sure that you have enough medication to last the entire time that you are away from home. It is quite likely that a foreign pharmacy will not honor your home country's prescription; therefore, it is best to bring a duplicate of the prescription with you so that you can show it to a local physician in the event that you require further medication.
        </p>
      </div>
    </div><br /><br />

    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">The Currency of the Country where you're moving</h2>
        <p class="font-italic text-muted mb-4">These days, using a credit or debit card issued in the foreign country is typically the best way to acquire access to funds but, you may wish to travel with some foreign currency or traveler's checks just in case something unexpected happens.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('currency.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div><br /><br />

    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src=<%= image_path('travel-size.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6">
        <h2 class="font-weight-light">Travel-Size Essential Toiletries</h2>
        <p class="font-italic text-muted mb-4">It is possible that more toiletries are considered "necessary" than others, however this will depend on the routine that you follow at home. Deodorant, toothpaste, a toothbrush, shampoo, conditioner, and body wash are the types of toiletries that we consider to be absolute necessities, and you should be sure to pack them in your carry-on bag
        </p>
      </div>
    </div><br /><br />

    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">Adapters and Converters for Electrical Current</h2>
        <p class="font-italic text-muted mb-4">It's probable that you'll want to carry a few chargers with you on your trip, whether they're for your smartphone or your laptop. In order to do so, you'll need a converter, and you may also need an adapter. Not all nations use the same electricity voltage, which means that merely altering the style of the plug might not be enough to make your charger operate – it could even be unsafe and short out the gadget. Be sure to research the types of plugs and voltage that are utilised in the country to which you will be travelling so that you can bring the appropriate adapters for all of your electronic equipment.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('universal-adapter.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>

    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src=<%= image_path('sanatiser.png') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6">
        <h2 class="font-weight-light">Hand sanitizer and face masks are another essential these days.</h2>
        <p class="font-italic text-muted mb-4">Prioritize protection! With the sudden spread of COVID-19, it’s advisable to maintain face masks and hand sanitizer with you at all times, to help protect yourself from germs and the chances of getting sick
        </p>
      </div>
    </div><br /><br />
    
    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1">
        <h2 class="font-weight-light">Cloths according to the country's culture.</h2>
        <p class="font-italic text-muted mb-4">Standards of modesty and the appropriateness of casual attire will differ from place to place, to an extent that is heavily influenced by the institution at which you are enrolled in your academic program.
          Keep in mind that shoes take up a lot of room. You will require three sets of shoes: a pair of flip-flops to use in the shower, a pair of comfortable walking shoes that are not running shoes, and a pair of dressier shoes to wear while going out or having dinner. Do your best to resist the temptation to bring any more pairs than that.
        </p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src=<%= image_path('cloths-according-to-culture.jpg') %> alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>
  </div>
</div>