config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboards#index'
  get 'about' => 'dashboards#about', as: 'about'
  get 'what_to_pack' => 'dashboards#what_to_pack', as: 'what_to_pack'
  get 'parents_guide' => 'dashboards#parents_guide', as: 'parents_guide'
  get 'contact' => 'dashboards#contact', as: 'contact'
  post 'new_contact' => 'dashboards#new_contact', as: 'new_contact'
  get 'my_application' => 'dashboards#my_application', as: 'my_application'
  post 'search' => 'dashboards#search', as: 'search'
  get 'unihub_applications/universities_for_country' => 'unihub_applications#universities_for_country',
      as: 'universities_for_country'
  get 'unihub_applications/degrees_for_university' => 'unihub_applications#degrees_for_university',
      as: 'degrees_for_university'
  get 'unihub_applications/courses_for_degree' => 'unihub_applications#courses_for_degree',
      as: 'courses_for_degree'

  resources :universities, only: [:show]
  resources :unihub_applications
  resources :courses, only: [:show]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="bg-light pb-5 myfooter">
  <div class="container text-center">
    <p class="font-italic text-muted mb-0">&copy; Copyrights UniHub All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
  <div class="container"><a href="<%= root_path %>" class="navbar-brand d-flex align-items-center"><img width=90 height=35 src="<%= image_path('unihub_logo.png') %>"></a>
    <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>
    <div id="navbarSupportedContent" class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item active"><a href="<%= root_path %>" class="nav-link font-italic"> Home </a></li>
        <li class="nav-item active"><a href="<%= about_path %>" class="nav-link font-italic"> About </a></li>
        <li class="nav-item active"><a href="<%= contact_path %>" class="nav-link font-italic"> Contact </a></li>
        <li class="nav-item active"><a href="<%= what_to_pack_path %>" class="nav-link font-italic"> What To Pack </a></li>
        <li class="nav-item active"><a href="<%= parents_guide_path %>" class="nav-link font-italic"> Parents Guide </a></li>
        <% if current_user && !current_user.unihub_applications.nil? %>
          <li class="nav-item active"><a href="<%= my_application_path %>" class="nav-link font-italic"> My Applications</a></li>
        <% end %>
      </ul>

      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item active"><a href="<%= edit_user_registration_path %>" class="nav-link font-italic"> <%= current_user.name.present? ? current_user.name : current_user.email %> </a></li>
          <li class="nav-item active"><a href="<%= destroy_user_session_path %>" class="nav-link font-italic"> Logout </a></li>
        <% else %>
          <li class="nav-item active"><a href="<%= new_user_registration_path %>" class="nav-link font-italic"> Register </a></li>
          <li class="nav-item active"><a href="<%= new_user_session_path %>" class="nav-link font-italic"> Login </a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %>
      <p class="alert alert-primary" role="alert"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    
  </body>
</html>